### ISSUE TITLE
Great Work! Suggestions for Including Related Work in Your Paper

### ISSUE THREAD

**Issue by bbsngg** [muirbench/MuirBench#1]
Hi Fei,

Thank you for your significant contribution with this impressive work.

We would like to kindly draw your attention to our previous work, [MileBench](https://arxiv.org/abs/2404.18532), which also includes multi-image data for benchmarking multimodal LLMs. Our work also uses various types of data to build the dataset, although it does not include the robust evaluation present in MuirBench. Given the comprehensive nature of your work, we believe that referencing MileBench would be a valuable addition to your related work section.

Thank you for your consideration.

**Comment by FeiWang96** [comment]
Hi @bbsngg ,

Thank you for the pointer. We're happy to cite your work in the next version of our paper. 

Best

**Comment by bbsngg** [comment]
Hi Fei,

Thank you for your positive response. We are very much looking forward to the release of your code and data. We hope to conduct some interesting experiments based on your work.

Additionally, we are excited to see more of your fascinating contributions in the future.

Best regards
