### ISSUE TITLE
Inconsistent Prompts

### ISSUE THREAD

**Issue by amitbcp** [muirbench/MuirBench#2]
Hi Team,

Great work. I was try to run the benchmarking and found that the Paper mentions a different prompt in the appendix while your integration with LMMS-Eval has a different prompt -

https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/536b70b4e5797f8bc51d46bc658e05db1d2b3c3b/lmms_eval/tasks/muirbench/muirbench.yaml#L15C19-L15C85

Can you please help with the prompt to be used to evaluate the Benchmark,

Also does every prompt starts with an image ?

**Comment by FeiWang96** [comment]
Hi Amit,

The prompt template used in our paper can be found at https://github.com/muirbench/MuirBench/blob/main/eval/utils/preprocess.py

The images may appear in any position in the prompt, not necessarily at the beginning.
